version: '3'

services:
    tests-microservice:
        container_name: tests-microservice
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/code
        ports:
            - 11111:11111
        env_file:
            - .env
        command: uvicorn app.main:app --host 0.0.0.0 --port 11111
        restart: unless-stopped